version: '3'
 
services:
  express: 
    container_name: chatexpr_express
    # build: .docker/docker-react.dockerfile
    build: 
      context: .
      dockerfile: .docker/express.dockerfile
    ports:
    - 3200:3200  
    volumes:
      # not override /app/node_modules
      - /app/node_modules
      - ./app:/app
    environment:
      DOCKER_CMP: "true"
    command: npm run dev